### ISSUE TITLE
Firehose client keeps crashing even after scaling up

### ISSUE THREAD

**Issue by ghost** [cloudfoundry-community/splunk-firehose-nozzle#36]
This nozzle app seems to be crashing again and again after few minutes it is running. We tried to scale up to maximum number of instances ( around 50 in Prod ) but still see the same behavior in all our environments.

bash-3.2$ cf a
Getting apps in org system / space splunk as ramakrishna.sajja@ge.com...
OK

name requested state instances memory disk urls
splunk-firehose-nozzle started 7/8 2G 1G
bash-3.2$ cf app splunk-firehose-nozzle
Showing health and status for app splunk-firehose-nozzle in org system / space splunk as ramakrishna.sajja@ge.com...
OK

requested state: started
instances: 7/8
usage: 2G x 8 instances
urls:
last uploaded: Fri Jun 9 14:01:51 UTC 2017
stack: cflinuxfs2
buildpack: https://github.com/cloudfoundry/go-buildpack#v1.7.14

state since cpu memory disk details
#0 crashing 2017-06-14 09:29:30 AM 16.9% 176.1M of 2G 48.1M of 1G
#1 crashing 2017-06-14 09:30:29 AM 0.0% 0 of 0 0 of 0
#2 crashing 2017-06-14 09:30:29 AM 18.9% 169.5M of 2G 48.2M of 1G
#3 crashing 2017-06-14 09:30:29 AM 35.6% 249.9M of 2G 48.2M of 1G
#4 crashing 2017-06-14 09:30:29 AM 38.6% 303.5M of 2G 48M of 1G
#5 crashing 2017-06-14 09:30:29 AM 10.0% 191.3M of 2G 48.1M of 1G
#6 crashing 2017-06-14 09:30:29 AM 31.6% 287.4M of 2G 48.2M of 1G
#7 crashing 2017-06-14 09:30:29 AM 32.1% 317.4M of 2G 48.5M of 1G

2017-06-14T10:25:18.08-0700 [App/1] OUT {"timestamp":"1497461118.082538605","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 3969 events","log_level":1,"data":{}}
2017-06-14T10:25:18.94-0700 [App/5] OUT {"timestamp":"1497461118.942245960","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 5127 events","log_level":1,"data":{}}
2017-06-14T10:25:22.31-0700 [App/0] OUT {"timestamp":"1497461122.311820269","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 25366 events","log_level":1,"data":{}}
2017-06-14T10:25:23.08-0700 [App/1] OUT {"timestamp":"1497461123.082553387","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 10120 events","log_level":1,"data":{}}
2017-06-14T10:25:23.94-0700 [App/5] OUT {"timestamp":"1497461123.942257881","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 6712 events","log_level":1,"data":{}}
2017-06-14T10:25:25.99-0700 [App/0] ERR [2017-06-14 17:25:25.995594742 +0000 UTC] Exception occurred! Message: Disconnected because nozzle couldn't keep up. Please try scaling up the nozzle. Details: <nil>
2017-06-14T10:25:25.99-0700 [App/0] ERR [2017-06-14 17:25:25.995487682 +0000 UTC] Exception occurred! Message: Error while reading from the firehose: %v Details: websocket: close 1008 (policy violation): Client did not respond to ping before keep-alive timeout expired.
2017-06-14T10:25:25.99-0700 [App/0] ERR [2017-06-14 17:25:25.995601484 +0000 UTC] Exception occurred! Message: Closing connection with traffic controller due to %v Details: websocket: close 1008 (policy violation): Client did not respond to ping before keep-alive timeout expired.
2017-06-14T10:25:25.99-0700 [App/0] OUT {"timestamp":"1497461125.995643377","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Failed connecting to Firehose","log_level":3,"data":{"error":"websocket: close 1008 (policy violation): Client did not respond to ping before keep-alive timeout expired.","trace":"goroutine 1 [running]:\ngithub.com/cloudfoundry-community/splunk-firehose-nozzle/vendor/code.cloudfoundry.org/lager.(*logger).Fatal(0xc820062360, 0x99c040, 0x1d, 0x7f021419c210, 0xc8327dc8c0, 0x0, 0x0, 0x0)\n\t/tmp/tmp.YAE2Dk5gg4/.go/src/github.com/cloudfoundry-community/splunk-firehose-nozzle/vendor/code.cloudfoundry.org/lager/logger.go:131 +0xc5\nmain.main()\n\t/tmp/tmp.YAE2Dk5gg4/.go/src/github.com/cloudfoundry-community/splunk-firehose-nozzle/main.go:88 +0xd87\n"}}
2017-06-14T10:25:26.00-0700 [App/0] ERR panic: websocket: close 1008 (policy violation): Client did not respond to ping before keep-alive timeout expired.
2017-06-14T10:25:26.00-0700 [App/0] ERR goroutine 1 [running]:
2017-06-14T10:25:26.00-0700 [App/0] ERR panic(0x87f160, 0xc8327dc8c0)
2017-06-14T10:25:26.00-0700 [App/0] ERR /tmp/cache/go1.6.3/go/src/runtime/panic.go:481 +0x3e6
2017-06-14T10:25:26.00-0700 [App/0] ERR github.com/cloudfoundry-community/splunk-firehose-nozzle/vendor/code.cloudfoundry.org/lager.(*logger).Fatal(0xc820062360, 0x99c040, 0x1d, 0x7f021419c210, 0xc8327dc8c0, 0x0, 0x0, 0x0)
2017-06-14T10:25:26.00-0700 [App/0] ERR /tmp/tmp.YAE2Dk5gg4/.go/src/github.com/cloudfoundry-community/splunk-firehose-nozzle/vendor/code.cloudfoundry.org/lager/logger.go:152 +0x642
2017-06-14T10:25:26.00-0700 [App/0] ERR main.main()
2017-06-14T10:25:26.00-0700 [App/0] ERR /tmp/tmp.YAE2Dk5gg4/.go/src/github.com/cloudfoundry-community/splunk-firehose-nozzle/main.go:88 +0xd87
2017-06-14T10:25:26.02-0700 [API/2] OUT App instance exited with guid cf1f417c-1905-4da3-a6db-1c9240170bef payload: {"cc_partition"=>"default", "droplet"=>"cf1f417c-1905-4da3-a6db-1c9240170bef", "version"=>"766481bc-b7c0-4c09-bfd2-1b8cdbcce31e", "instance"=>"feb832f77dd348018a8cfcb24c6a8902", "index"=>0, "reason"=>"CRASHED", "exit_status"=>2, "exit_description"=>"app instance exited", "crash_timestamp"=>1497461126}

**Comment by chenziliang** [comment]
@Ram2225, May i ask how big is your env ? What is the throughput or EPS (event per second) firehose will publish ?

**Comment by Ram2225** [comment]
@chenziliang , It is a vast environment. It publishes around 50k events per second.

**Comment by chenziliang** [comment]
This appears a performance issue in the current implementation.
@Ram2225  May i ask what is the deployment architecture you have ? 50 Nozzles ->  HFW -> Indexers ?

**Comment by cholick** [comment]
It would also be useful to know if `ADD_APP_INFO` is set to true and what type of events you're listening for @Ram2225

**Comment by Ram2225** [comment]
@chenziliang , Currently it is running on 50 instances and we have 2 HFW and 10 indexers.

@cholick , unfortunately we cannot set this ADD_APP_INFO to true since this is in Production and enabling this will increase load on the API machines in step with the number of running apps, as each Nozzle will populate a cache of app metadata.

**Comment by chenziliang** [comment]
@Ram2225 If there is only 2 HFWs, i think they have challenges to handle 50K events per second. May i ask if you have considered the following setups:
1) Setup HEC on 10 indexers with the same HEC token
2)  Setup a load balancer before your 10 indexers
3) Configure 50 Nozzles talk to the load balancer directly instead of talking to local 2 HFWs.

**Comment by chenziliang** [comment]
@Ram2225  Could you please try issue42-scale-up-nozzle branch https://github.com/cloudfoundry-community/splunk-firehose-nozzle/tree/feature/issue42-scale-up-nozzle

**Comment by chenziliang** [comment]
This is a big sign of splunk nozzle can't keep up with the HEC posting since it was posting several thousands events in one shot, events are accumulating in memory. Code in dev branch should mitigate this problem

```
{"timestamp":"1497461118.082538605","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 3969 events","log_level":1,"data":{}}
2017-06-14T10:25:18.94-0700 [App/5] OUT {"timestamp":"1497461118.942245960","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 5127 events","log_level":1,"data":{}}
2017-06-14T10:25:22.31-0700 [App/0] OUT {"timestamp":"1497461122.311820269","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 25366 events","log_level":1,"data":{}}
2017-06-14T10:25:23.08-0700 [App/1] OUT {"timestamp":"1497461123.082553387","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 10120 events","log_level":1,"data":{}}
2017-06-14T10:25:23.94-0700 [App/5] OUT {"timestamp":"1497461123.942257881","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 6712 events","log_level":1,"data":{}}
2017-06-14T10:25:25
...
```

**Comment by psychickita** [comment]
@chenziliang - please help me understand what in this log leads you to believe the nozzle is not keeping up.

**Comment by chenziliang** [comment]
Number of events are batched in the one POST as i mentioned above

**Comment by psychickita** [comment]
So you are saying the number is too large, because nozzle is not keeping up? If so, what is the cutoff number in your opinion or some kind of a formula?

**Comment by coryjett** [comment]
Was this ever resolved?  We are seeing similar behavior with a much smaller number of messages.

```
   2017-08-14T08:56:02.20-0500 [APP/8] ERR [2017-08-14 08:56:02.201994238 -0500 CDT] Exception occurred! Message: Closing connection with traffic controller due to %v Details: websocket: close 1008 (policy violation): Client did not respond to ping before keep-alive timeout expired.
   2017-08-14T08:56:02.20-0500 [APP/8] ERR [2017-08-14 08:56:02.20175629 -0500 CDT] Exception occurred! Message: Error while reading from the firehose: %v Details: websocket: close 1008 (policy violation): Client did not respond to ping before keep-alive timeout expired.
   2017-08-14T08:56:02.20-0500 [APP/8] ERR [2017-08-14 08:56:02.201976893 -0500 CDT] Exception occurred! Message: Disconnected because nozzle couldn't keep up. Please try scaling up the nozzle. Details: <nil>
```

Here is a sample of the number of logs we are posting to Splunk (as you can see, it isn't a large number of events):
```
   2017-08-14T08:56:12.59-0500 [APP/7] OUT {"timestamp":"1502718972.591456652","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 254 events","log_level":1,"data":{}}
   2017-08-14T08:56:13.00-0500 [APP/6] OUT {"timestamp":"1502718973.009088039","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 317 events","log_level":1,"data":{}}
   2017-08-14T08:56:13.09-0500 [APP/9] OUT {"timestamp":"1502718973.096106052","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 189 events","log_level":1,"data":{}}
   2017-08-14T08:56:13.17-0500 [APP/0] OUT {"timestamp":"1502718973.173720837","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 339 events","log_level":1,"data":{}}
   2017-08-14T08:56:13.63-0500 [APP/10] OUT {"timestamp":"1502718973.617817163","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 7 events","log_level":1,"data":{}}
   2017-08-14T08:56:13.89-0500 [APP/3] OUT {"timestamp":"1502718973.897183657","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 188 events","log_level":1,"data":{}}
   2017-08-14T08:56:13.95-0500 [APP/2] OUT {"timestamp":"1502718973.952148914","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 56 events","log_level":1,"data":{}}
   2017-08-14T08:56:14.20-0500 [APP/13] OUT {"timestamp":"1502718974.204745531","source":"splunk-nozzle-logger","message":"splunk-nozzle-logger.Posting 382 events","log_level":1,"data":{}}
```

**Comment by chenziliang** [comment]
Please use develop branch and try. Please keep the HEC batch size in a reasonable size say 100 ~ 1000

**Comment by coryjett** [comment]
Thank you.  The develop branch appears to be stable.  Is the HEC batch size configurable in the nozzle?

**Comment by chenziliang** [comment]
yes, you can find the details in readme markdown. by default it is 1000. Note the more Splunk nozzle you scale out, the smaller batch size you probably need to apply. If you can tell what kind of volume you have in prod, I may come up with a better config suggestion :).

**Comment by coryjett** [comment]
Perfect, thank you 👍 .  We are pushing about 1500 events/s.

**Comment by chenziliang** [comment]
2 nozzle with the same subscription ID with HEC batch size to 100 should handle this load

**Comment by chenziliang** [comment]
@coryjett, may I ask what is your deployment architecture in prod? Nozzle, Splunk Heavy forwarder, load balancer, Splunk indexer cluster. And how you deploy the Splunk nozzle ? Deploy it as a PCF app?

Thank you very much!
